
( function(win, doc) {
            var audioPlayer = doc.getElementById("music");
            var subtitles = doc.getElementById("subtitles");
						var time=9;
						 var syncData =[

               { "start": time,"end": time+0.50,"text": "Many " },
               { "start": time+0.50,"end": time+1.00,"text": "clothing " },
               { "start": time+1.00,"end": time+1.50,"text": "brands " },
               { "start": time+1.50,"end": time+2.00,"text": "have " },
               { "start": time+1.80,"end": time+2.30,"text": "failed  " },
               { "start": time+2.50,"end": time+3.00,"text": "because " },
               { "start": time+3.00,"end": time+3.50,"text": "they did " },
               { "start": time+3.50,"end": time+4.00,"text": "not design " },
               { "start": time+4.00,"end": time+4.50,"text": "marketable " },
               { "start": time+4.50,"end": time+5.00,"text": "products " },
               { "start": time+5.00,"end": time+5.50,"text": "using " },
               { "start": time+5.70,"end": time+6.20,"text": "a good " },
               { "start": time+6.20,"end": time+6.70,"text": "business " },
               { "start": time+6.70,"end": time+7.20,"text": "plan. " },
               { "start": time+7.70,"end": time+8.20,"text": "Often " },
               { "start": time+8.20,"end": time+8.70,"text": "times " },
               { "start": time+8.90,"end": time+9.40,"text": "clothing " },
               { "start": time+9.30,"end": time+9.80,"text": "brand " },
               { "start": time+9.70,"end": time+10.20,"text": "owners " },
               { "start": time+10.00,"end": time+10.50,"text": "do not  " },
               { "start": time+10.50,"end": time+11.00,"text": "use their " },
               { "start": time+11.00,"end": time+11.50,"text": "capital " },
               { "start": time+11.50,"end": time+12.00,"text": "in efficient " },
               { "start": time+12.00,"end": time+12.50,"text": "ways. " },
               { "start": time+12.50,"end": time+13.00,"text": "They " },
               { "start": time+13.00,"end": time+13.50,"text": "can be " },
               { "start": time+13.50,"end": time+14.00,"text": "surprised " },
               { "start": time+14.00,"end": time+14.50,"text": "with " },
               { "start": time+14.50,"end": time+15.00,"text": "unexpected " },
               { "start": time+15.00,"end": time+15.50,"text": "costs " },
               { "start": time+15.50,"end": time+16.00,"text": "and " },
               { "start": time+16.00,"end": time+16.50,"text": "do not " },
               { "start": time+16.50,"end": time+17.00,"text": "run the " },
               { "start": time+17.00,"end": time+17.50,"text": "business " },
               { "start": time+17.50,"end": time+18.00,"text": "in the " },
               { "start": time+17.80,"end": time+18.30,"text": "most effi" },
               { "start": time+18.30,"end": time+18.80,"text": "cient and " },
               { "start": time+19.00,"end": time+19.50,"text": "professional " },
               { "start": time+19.50,"end": time+20.00,"text": "way. " },
               { "start": time+20.20,"end": time+20.70,"text": "The " },
               { "start": time+20.50,"end": time+21.00,"text": "goal " },
               { "start": time+21.00,"end": time+21.50,"text": "of this " },
               { "start": time+21.50,"end": time+22.00,"text": "proyect " },
               { "start": time+22.00,"end": time+22.50,"text": "is to " },
               { "start": time+22.50,"end": time+23.00,"text": "create " },
               { "start": time+23.00,"end": time+23.50,"text": "a clothing " },
               { "start": time+23.50,"end": time+24.00,"text": "brand " },
               { "start": time+24.00,"end": time+24.50,"text": "that " },
               { "start": time+24.50,"end": time+25.00,"text": "incorporates " },
               { "start": time+25.00,"end": time+25.50,"text": "innovative " },
               { "start": time+25.50,"end": time+26.00,"text": "designs " },
               { "start": time+26.00,"end": time+26.50,"text": "along " },
               { "start": time+26.50,"end": time+27.00,"text": "with an " },
               { "start": time+27.00,"end": time+27.50,"text": "effective " },
               { "start": time+27.50,"end": time+28.00,"text": "business " },
               { "start": time+28.00,"end": time+28.50,"text": "model. " },
               { "start": time+29.00,"end": time+29.50,"text": "This " },
               { "start": time+29.50,"end": time+30.00,"text": "includes " },
               { "start": time+30.00,"end": time+30.50,"text": "using " },
               { "start": time+30.50,"end": time+31.00,"text": "a process " },
               { "start": time+31.00,"end": time+31.50,"text": "called " },
               { "start": time+31.50,"end": time+32.00,"text": "'decision " },
               { "start": time+32.00,"end": time+32.50,"text": "analysis', " },
               { "start": time+32.50,"end": time+33.00,"text": "during " },
               { "start": time+33.00,"end": time+33.50,"text": "planning " },
               { "start": time+33.50,"end": time+34.00,"text": "phase. " },
               { "start": time+34.50,"end": time+35.00,"text": "Creating " },
               { "start": time+35.00,"end": time+35.50,"text": "quality " },
               { "start": time+35.50,"end": time+36.00,"text": "products " },
               { "start": time+36.00,"end": time+36.50,"text": "while being " },
               { "start": time+36.50,"end": time+37.00,"text": "as cost " },
               { "start": time+37.00,"end": time+37.50,"text": "effective " },
               { "start": time+37.50,"end": time+38.00,"text": "as possible " },
               { "start": time+38.00,"end": time+38.50,"text": "is " },
               { "start": time+38.50,"end": time+39.00,"text": "vital " },
               { "start": time+39.00,"end": time+39.50,"text": "to " },
               { "start": time+39.50,"end": time+40.00,"text": "success " },
               { "start": time+40.00,"end": time+40.50,"text": "in the " },
               { "start": time+40.30,"end": time+40.80,"text": "fashion " },
               { "start": time+40.80,"end": time+41.30,"text": "industry. " },
               { "start": time+42.00,"end": time+42.50,"text": "Industrial " },
               { "start": time+42.50,"end": time+43.00,"text": "engineering " },
               { "start": time+43.00,"end": time+43.50,"text": "techniques " },
               { "start": time+43.50,"end": time+44.00,"text": "will be " },
               { "start": time+44.00,"end": time+44.50,"text": "what " },
               { "start": time+44.50,"end": time+45.00,"text": "makes a " },
               { "start": time+44.80,"end": time+45.30,"text": "brand " },
               { "start": time+45.30,"end": time+45.80,"text": "distinguish " },
               { "start": time+45.80,"end": time+46.30,"text": "itself " },
               { "start": time+46.30,"end": time+46.80,"text": "from " },
               { "start": time+46.60,"end": time+47.10,"text": "similar " },
               { "start": time+47.10,"end": time+47.60,"text": "competitors. " },
               { "start": time+48.00,"end": time+48.50,"text": "Every " },
               { "start": time+48.50,"end": time+49.00,"text": "business " },
               { "start": time+49.00,"end": time+49.50,"text": "needs " },
               { "start": time+49.50,"end": time+50.00,"text": "to be " },
               { "start": time+50.00,"end": time+50.60,"text": "profitable " },
               { "start": time+50.50,"end": time+51.00,"text": "to be " },
               { "start": time+51.00,"end": time+51.50,"text": "successful, " },
               { "start": time+52.00,"end": time+52.50,"text": "and this " },
               { "start": time+52.50,"end": time+53.00,"text": "proyect " },
               { "start": time+53.00,"end": time+53.50,"text": "will show " },
               { "start": time+53.50,"end": time+54.00,"text": "how to " },
               { "start": time+54.00,"end": time+54.50,"text": "achieve " },
               { "start": time+54.50,"end": time+55.00,"text": "success " },
               { "start": time+55.00,"end": time+55.50,"text": "with minimal " },
               { "start": time+55.50,"end": time+56.00,"text": "initial " },
               { "start": time+56.00,"end": time+56.50,"text": "capital. " },
               { "start": time+57.00,"end": time+57.50,"text": "These " },
               { "start": time+57.50,"end": time+58.00,"text": "methods " },
               { "start": time+58.00,"end": time+58.50,"text": "along " },
               { "start": time+58.50,"end": time+59.00,"text": "with " },
               { "start": time+59.00,"end": time+59.50,"text": "unique " },
               { "start": time+59.50,"end": time+60.00,"text": "designs " },
               { "start": time+60.00,"end": time+60.50,"text": "will " },
               { "start": time+60.50,"end": time+61.00,"text": "pave " },
               { "start": time+61.00,"end": time+61.50,"text": "the way " },
               { "start": time+61.50,"end": time+62.00,"text": "to a " },
               { "start": time+62.00,"end": time+62.50,"text": "successful " },
               { "start": time+62.50,"end": time+63.00,"text": "clothing " },
               { "start": time+62.80,"end": time+63.30,"text": "line. " },
               { "start": time+66.50,"end": time+67.00,"text": "One of " },
               { "start": time+67.00,"end": time+67.50,"text": "the most " },
               { "start": time+67.50,"end": time+68.00,"text": "often " },
               { "start": time+68.00,"end": time+68.50,"text": "used " },
               { "start": time+68.50,"end": time+69.00,"text": "tools " },
               { "start": time+69.00,"end": time+69.60,"text": "in a residential " },
               { "start": time+69.50,"end": time+70.00,"text": "kitchen " },
               { "start": time+70.00,"end": time+70.50,"text": "is the " },
               { "start": time+70.50,"end": time+71.00,"text": "cook's " },
               { "start": time+71.00,"end": time+71.50,"text": "favorite " },
               { "start": time+71.50,"end": time+72.00,"text": "pot " },
               { "start": time+72.00,"end": time+72.50,"text": "or pan. " },
               { "start": time+73.00,"end": time+73.50,"text": "And because " },
               { "start": time+73.50,"end": time+74.00,"text": "many " },
               { "start": time+74.00,"end": time+74.50,"text": "people " },
               { "start": time+74.50,"end": time+75.00,"text": "do not like " },
               { "start": time+75.00,"end": time+75.50,"text": "washing " },
               { "start": time+75.50,"end": time+76.00,"text": "the dishes " },
               { "start": time+76.00,"end": time+76.50,"text": "by hand " },
               { "start": time+76.50,"end": time+77.00,"text": "there is " },
               { "start": time+77.00,"end": time+77.50,"text": "a  " },
               { "start": time+77.50,"end": time+78.00,"text": "need " },
               { "start": time+78.00,"end": time+78.50,"text": "to clean " },
               { "start": time+78.50,"end": time+79.00,"text": "pans " },
               { "start": time+79.00,"end": time+79.50,"text": "that are " },
               { "start": time+79.50,"end": time+80.00,"text": "used for " },
               { "start": time+80.00,"end": time+80.50,"text": "each " },
               { "start": time+80.40,"end": time+80.90,"text": "meal " },
               { "start": time+80.80,"end": time+81.50,"text": "inmediately. " },
               { "start": time+82.00,"end": time+82.50,"text": "Currently " },
               { "start": time+82.50,"end": time+83.00,"text": "there are " },
               { "start": time+83.00,"end": time+83.50,"text": "few " },
               { "start": time+83.50,"end": time+84.00,"text": "products " },
               { "start": time+84.00,"end": time+84.50,"text": "that " },
               { "start": time+84.50,"end": time+85.00,"text": "speed up " },
               { "start": time+85.00,"end": time+85.50,"text": "the " },
               { "start": time+85.30,"end": time+85.80,"text": "hand washing " },
               { "start": time+85.80,"end": time+86.30,"text": "process. " },
               { "start": time+87.00,"end": time+87.50,"text": "Also " },
               { "start": time+87.50,"end": time+88.00,"text": "we feel that " },
               { "start": time+88.00,"end": time+88.50,"text": "a product " },
               { "start": time+88.50,"end": time+89.00,"text": "that " },
               { "start": time+89.00,"end": time+89.50,"text": "speeds up " },
               { "start": time+89.50,"end": time+90.00,"text": "hand washing " },
               { "start": time+90.50,"end": time+91.00,"text": "may be " },
               { "start": time+91.00,"end": time+91.50,"text": "useful " },
               { "start": time+91.50,"end": time+92.00,"text": "in areas " },
               { "start": time+92.00,"end": time+92.50,"text": "where " },
               { "start": time+92.50,"end": time+93.00,"text": "full-size " },
               { "start": time+93.00,"end": time+93.50,"text": "dishwashers " },
               { "start": time+93.70,"end": time+94.20,"text": "are not " },
               { "start": time+94.20,"end": time+94.70,"text": "common. " },
               { "start": time+95.00,"end": time+95.50,"text": "Our " },
               { "start": time+95.50,"end": time+96.00,"text": "team " },
               { "start": time+96.00,"end": time+96.50,"text": "will work " },
               { "start": time+96.00,"end": time+96.50,"text": " " },
               { "start": time+96.50,"end": time+97.00,"text": "collaboratively " },
               { "start": time+97.00,"end": time+97.50,"text": "to solve " },
               { "start": time+97.90,"end": time+98.40,"text": "this problem. " },
               { "start": time+99.50,"end": time+100.00,"text": "After " },
               { "start": time+100.00,"end": time+100.50,"text": "conducting " },
               { "start": time+100.50,"end": time+101.00,"text": "a wide " },
               { "start": time+101.00,"end": time+101.50,"text": "ranging " },
               { "start": time+101.50,"end": time+102.00,"text": "market " },
               { "start": time+102.00,"end": time+102.50,"text": "survey, " },
               { "start": time+102.50,"end": time+103.00,"text": "we designed " },
               { "start": time+103.00,"end": time+103.50,"text": "our " },
               { "start": time+103.50,"end": time+104.00,"text": "first " },
               { "start": time+104.00,"end": time+104.50,"text": "iteration " },
               { "start": time+104.50,"end": time+105.00,"text": "of a " },
               { "start": time+105.00,"end": time+105.50,"text": "device " },
               { "start": time+106.00,"end": time+106.50,"text": "which " },
               { "start": time+106.30,"end": time+107.00,"text": "can fill " },
               { "start": time+107.00,"end": time+107.50,"text": "the existing " },
               { "start": time+107.50,"end": time+108.00,"text": "gap " },
               { "start": time+108.00,"end": time+108.50,"text": "between " },
               { "start": time+108.50,"end": time+109.00,"text": "hand washing " },
               { "start": time+109.10,"end": time+109.60,"text": "and washing " },
               { "start": time+109.50,"end": time+110.00,"text": "dishes " },
               { "start": time+110.00,"end": time+110.50,"text": "in a " },
               { "start": time+110.50,"end": time+111.00,"text": "dishwasher. " },
               { "start": time+112.00,"end": time+112.50,"text": "We " },
               { "start": time+112.40,"end": time+113.10,"text": "succesfully " },
               { "start": time+113.00,"end": time+113.50,"text": "built " },
               { "start": time+113.50,"end": time+114.50,"text": "a single pan " },
               { "start": time+114.40,"end": time+115.00,"text": "dishwasher " },
               { "start": time+115.00,"end": time+115.50,"text": "which " },
               { "start": time+115.50,"end": time+116.00,"text": "simulates " },
               { "start": time+116.00,"end": time+116.50,"text": "hand washing " },
               { "start": time+116.50,"end": time+117.00,"text": "to clean " },
               { "start": time+117.00,"end": time+117.50,"text": "non" },
               { "start": time+117.50,"end": time+118.00,"text": "stick " },
               { "start": time+118.00,"end": time+118.50,"text": "frying " },
               { "start": time+118.50,"end": time+119.00,"text": "pans. " },
               { "start": time+119.50,"end": time+120.00,"text": "After " },
               { "start": time+120.00,"end": time+120.50,"text": "testing " },
               { "start": time+121.00,"end": time+121.50,"text": "we are " },
               { "start": time+121.20,"end": time+121.70,"text": "ready " },
               { "start": time+121.70,"end": time+122.20,"text": "to share " },
               { "start": time+122.20,"end": time+122.70,"text": "our results. " },


                ];

            createSubtitle();

            function createSubtitle()
            {
                var element;
                for (var i = 0; i < syncData.length; i++) {
                    element = doc.createElement('a');
                    element.setAttribute("id", "c_" + i);
                    element.setAttribute("class","rd-word");
                    element.setAttribute("data-inicio", syncData[i].start);
                    element.innerText = syncData[i].text + "";
                    subtitles.appendChild(element);
                }
            }

            audioPlayer.addEventListener("timeupdate", function(e){
                syncData.forEach(function(element, index, array){
                    if( audioPlayer.currentTime >= element.start && audioPlayer.currentTime <= element.end ){
                      $(".rd-word").css("color","rgba(0,0,0,0.8)");
                      for(i=0;i<=index; i++){
                        subtitles.children[i].style.color = '#279CD7';
                      }
                    }
                });
            });

        }(window, document));
